### ISSUE TITLE
Read temp sensor

### ISSUE THREAD

**Issue by JonathanFager** [BryggansBryggeri/bryggio#7]
DoD: 
- [x] Read temperature from One-wire sensors
- [x] Indicate errors

**Comment by jackonelli** [comment]
Jag tog bort "ge namn". Backend/config kommer ge den ett hårt id i 0.1.0.

Sen kan frontenden ha ett mer logiskt namn för plottar och så men det är disjunkt från den här issuen.

**Comment by jackonelli** [comment]
Confirmed sensors working on motherboard v1.0.
This indirectly means that all is fine for bryggio since "reading measurements" is basically reading from a file, which I, as stated, have confirmed does exist and works.

There is prolly a cooler way of doing it, see for instance https://crates.io/crates/onewire
but it is unstable and a bit out of my league.

**Comment by jackonelli** [comment]
I removed the filtering task since filtering will be done in a independent step
